      SUBROUTINE SYMPRD (N1,N2,N3,N4,N,M,X,A,T,Z)
      DOUBLE PRECISION   X(N1,M)
      DOUBLE PRECISION   A(N2,N)
      DOUBLE PRECISION   T(N3,M)
      DOUBLE PRECISION   Z(N4,M)
CF
CF  DESCRIPTION:
CF
CF  FORM MATRIX PRODUCT T = X-TRANSPOSE * A * X
C
CI  ON INPUT:
CI  X IS N X M IN N1 X M ARRAY
CI  A IS N X N IN N2 X N ARRAY
CI  Z IS TEMPORARY N4 X M ARRAY, WITH N4 >= N
CI
C  ROUTINES CALLED:
C  MMUL,XTY
C
C  WRITTEN BY:  J. DOUGLAS BIRDWELL
C               DEPT. OF ELEC. ENGR.
C               FERRIS 311
C               UNIVERSITY OF TENNESSEE
C               KNOXVILLE, TN  37996-2100
C               (615) 974-5468
C
      CALL MMUL (N2,N1,N4,M,N,N,A,X,Z)
      CALL XTY (N1,N4,N3,N,M,M,X,Z,T)
      RETURN
      END
